cc_library(
	name = "image-canvas-example-lib",
	srcs = ["ImageCanvasExample.cpp"],
	deps = [
		"//:die-tk-base",
	],
)

cc_binary(
	name = "image-canvas-example",
	deps = [
		":image-canvas-example-lib",
		"//:die-tk",
	],
)
